Revert "fix: 파일 업데이트"
This reverts commit 33004a10d0aaf7e7ebec484abc464dc6fa807c22, reversing
changes made to d8e9dbdbad74d13d5fa2cf5b968cb52698516016.

diff --git a/tools/release b/tools/release
--- a/tools/release
+++ b/tools/release
@@ -70,14 +70,12 @@ _check_git() {
     exit 1
   fi
 
-  $opt_pre || (
-    if [[ $working_branch != "$DEFAULT_BRANCH" &&
-      $working_branch != hotfix/* &&
-      $working_branch != "$PROD_BRANCH" ]]; then
-      echo "> Abort: Please run on the default, release or patch branch."
-      exit 1
-    fi
-  )
+  if [[ $working_branch != "$DEFAULT_BRANCH" &&
+    $working_branch != hotfix/* &&
+    $working_branch != "$PROD_BRANCH" ]]; then
+    echo "> Abort: Please run on the default, release or patch branch."
+    exit 1
+  fi
 }
 
 _check_src() {
@@ -151,16 +149,14 @@ branch() {
   fi
 }
 
-## Build a Gem package
+## Build a gem package
 build_gem() {
-  git checkout "$PROD_BRANCH"
-
   # Remove unnecessary theme settings
   sed -i "s/^img_cdn:.*/img_cdn:/;s/^avatar:.*/avatar:/" _config.yml
   rm -f ./*.gem
 
   npm run build
-  git add "$JS_DIST" -f # add JS distribution files to gem
+  git add "$JS_DIST" -f # add JS dist to gem
   gem build "$GEM_SPEC"
   cp "$JS_DIST"/* "$BACKUP_PATH"
 
@@ -170,9 +166,6 @@ build_gem() {
 
   # restore the dist files for future development
   mkdir -p "$JS_DIST" && cp "$BACKUP_PATH"/* "$JS_DIST"
-
-  # back to the default branch
-  git checkout "$DEFAULT_BRANCH"
 }
 
 main() {
